import type { Metadata } from "next";
import Providers from "../components/Providers";
import React from "react";
import "../../src/styles/globals.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): Promise<React.ReactElement> {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900 font-sans">
        <Providers>
          <Toaster />
          {children}
        </Providers>
      </body>
    </html>
  );
}
